name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t salarymodel
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.MLOPS_ACTIVITY }}
    - name: Tag the Docker image
      run: docker tag salarymodel:latest zaid056/first-action-docker-project:latest
    - name: Push the Docker image
      run: docker push zaid056/first-action-docker-project:latest  
